galaxy_info:
  author: Cloud Codger
  description: Prometheus exporter for Proxmox VE hosts

  license: GPL-2.0-or-later

  min_ansible_version: '2.50'

  galaxy_tags:
    - cluster
    - hypervisor
    - proxmox
    - pve
    - virtualization

dependencies: []
