---
galaxy_info:
  author: Cloud Codger
  description: Proxmox Datacenter Initial Config

  license: GPL-2.0-or-later

  min_ansible_version: '2.15'

  galaxy_tags:
    - cluster
    - hypervisor
    - proxmox
    - pve
    - virtualization

dependencies: []
